version: '3.8'

services:
    nginx:
        image: nginx:1.25-alpine
        container_name: nginx-${DRONE_REPO_NAME}-dev
        restart: unless-stopped
        ports:
            - ${HTTP_PORT_DEV}:80
        volumes:
            - ./nginx:/etc/nginx/conf.d/
            - php_socket:/var/run/php
            - .:/var/www/html
        depends_on:
            - php
        networks:
            - symfony


    php:
        container_name: php-${DRONE_REPO_NAME}-dev
        build:
            context: .
            args:
                - CACHEBUST=$(date +%s)
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
            - .:/var/www/html
        networks:
            - symfony

volumes:
    php_socket:

networks:
    symfony:
        name: symfony-${DRONE_REPO_NAME}-dev
